# Generated by Django 5.2.6 on 2025-10-03 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fsToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(help_text='the token', max_length=2048, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='pqAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_title', models.CharField(help_text='title of the zip', max_length=1024, null=True)),
                ('pq_id', models.IntegerField(default=0, help_text='id of the preprint')),
                ('pq_json', models.TextField(help_text='the json convert', null=True)),
                ('title', models.CharField(help_text='title of the preprint', max_length=2048, null=True)),
                ('received', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(default='', help_text='what went wrong. what went write.', null=True)),
                ('status', models.CharField(default='ready-for-push', help_text='status and maybe error message', max_length=2048, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='pqFsAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fs_id', models.IntegerField(default=0, help_text='filled in after successful upload to figshare')),
                ('status', models.CharField(default='ready-for-push', help_text='status and maybe error message', max_length=2048, null=True)),
                ('response', models.CharField(default='', help_text='response status from FS', max_length=2048, null=True)),
                ('link', models.CharField(help_text='link created for reference on fs', max_length=1024, null=True)),
                ('attempted', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(default='', help_text='what went wrong. what went write.', null=True)),
                ('fs_attempt_json', models.TextField(help_text='the json attempt', null=True)),
                ('pqa_fk', models.ForeignKey(help_text='FK for pqAttempt', on_delete=django.db.models.deletion.CASCADE, to='etds.pqattempt')),
            ],
        ),
    ]
