# Generated by Django 5.2.6 on 2026-04-15 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etds', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pqattempt',
            old_name='received',
            new_name='date_saved',
        ),
        migrations.AddField(
            model_name='pqattempt',
            name='other_files',
            field=models.TextField(help_text='other files that were included in the zip', null=True),
        ),
    ]
