# Generated by Django 5.1.7 on 2025-03-28 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='fsAttempts',
            new_name='fsAttempt',
        ),
        migrations.RenameModel(
            old_name='oaMessages',
            new_name='oaMessage',
        ),
    ]
