# Generated by Django 5.1.7 on 2025-03-28 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0002_rename_fsattempts_fsattempt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fsattempt',
            name='fs_attempt_json',
            field=models.TextField(default=None, help_text='the json attempt'),
        ),
        migrations.AlterField(
            model_name='fsattempt',
            name='fs_id',
            field=models.IntegerField(default=0, help_text='filled in after successful upload to figshare'),
        ),
        migrations.AlterField(
            model_name='fsattempt',
            name='link',
            field=models.CharField(default=None, help_text='link created for reference on fs', max_length=1024),
        ),
        migrations.AlterField(
            model_name='fsattempt',
            name='status',
            field=models.CharField(default=None, help_text='status and maybe error message', max_length=2048),
        ),
        migrations.AlterField(
            model_name='oamessage',
            name='message_id',
            field=models.IntegerField(default=0, help_text='id of the messages'),
        ),
        migrations.AlterField(
            model_name='oamessage',
            name='message_json',
            field=models.TextField(default=None, help_text='the json received'),
        ),
        migrations.AlterField(
            model_name='oamessage',
            name='message_title',
            field=models.CharField(default=None, help_text='title of the article', max_length=1024),
        ),
        migrations.AlterField(
            model_name='oamessage',
            name='status',
            field=models.CharField(default=None, help_text='status and maybe error message', max_length=2048),
        ),
    ]
