# Generated by Django 5.1.7 on 2025-03-28 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0003_alter_fsattempt_fs_attempt_json_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fsattempt',
            name='fs_attempt_json',
            field=models.TextField(help_text='the json attempt', null=True),
        ),
        migrations.AlterField(
            model_name='fsattempt',
            name='link',
            field=models.CharField(help_text='link created for reference on fs', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='fsattempt',
            name='status',
            field=models.CharField(help_text='status and maybe error message', max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='oamessage',
            name='message_json',
            field=models.TextField(default=None, help_text='the json received', null=True),
        ),
        migrations.AlterField(
            model_name='oamessage',
            name='message_title',
            field=models.CharField(help_text='title of the article', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='oamessage',
            name='status',
            field=models.CharField(help_text='status and maybe error message', max_length=2048, null=True),
        ),
    ]
