# Generated by Django 5.1.7 on 2025-04-30 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0004_alter_fsattempt_fs_attempt_json_alter_fsattempt_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='oaMessageAttempts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempted', models.DateTimeField(auto_now_add=True)),
                ('total_messages', models.IntegerField(default=0, help_text='how many messages we gots')),
                ('last_offset', models.IntegerField(default=0, help_text='how far back')),
            ],
        ),
        migrations.AlterField(
            model_name='oamessage',
            name='status',
            field=models.CharField(default='ready', help_text='status and maybe error message', max_length=2048, null=True),
        ),
    ]
