# Generated by Django 5.1.7 on 2025-04-30 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0005_oamessageattempts_alter_oamessage_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='repoLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='cc short code', max_length=1024, null=True)),
                ('name', models.CharField(help_text='longform', max_length=1024, null=True)),
                ('url', models.CharField(help_text='url for this license', max_length=1024, null=True)),
            ],
        ),
    ]
