# Generated by Django 5.1.7 on 2025-05-05 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0006_repolicense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repolicense',
            name='name',
            field=models.CharField(help_text='longform', max_length=1024, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='repolicense',
            name='url',
            field=models.CharField(help_text='url for this license', max_length=1024, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='repolicense',
            name='value',
            field=models.CharField(help_text='cc short code', max_length=1024, null=True, unique=True),
        ),
    ]
