# Generated by Django 5.1.7 on 2025-05-05 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0007_alter_repolicense_name_alter_repolicense_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oamessage',
            name='note',
            field=models.TextField(default=None, help_text='what went wrong. what went write.', null=True),
        ),
    ]
