# Generated by Django 5.1.7 on 2025-05-06 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0008_oamessage_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repolicense',
            name='url',
            field=models.CharField(help_text='url for this license', max_length=1024, null=True),
        ),
    ]
