# Generated by Django 5.1.7 on 2025-05-06 20:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0009_alter_repolicense_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fsattempt',
            old_name='oa_id',
            new_name='oama_fk',
        ),
        migrations.AddField(
            model_name='fsattempt',
            name='attempted',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='oamessage',
            name='note',
            field=models.TextField(default='', help_text='what went wrong. what went write.', null=True),
        ),
    ]
