# Generated by Django 5.1.7 on 2025-05-06 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0010_rename_oa_id_fsattempt_oama_fk_fsattempt_attempted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fsattempt',
            name='status',
            field=models.CharField(default='ready-for-push', help_text='status and maybe error message', max_length=2048, null=True),
        ),
    ]
