# Generated by Django 5.1.7 on 2025-05-06 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0011_alter_fsattempt_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='fsattempt',
            name='note',
            field=models.TextField(default='', help_text='what went wrong. what went write.', null=True),
        ),
    ]
