# Generated by Django 5.1.7 on 2025-05-06 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0012_fsattempt_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='fsattempt',
            name='response',
            field=models.CharField(default='', help_text='response status from FS', max_length=2048, null=True),
        ),
    ]
