# Generated by Django 4.0.4 on 2025-06-27 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0013_fsattempt_response'),
    ]

    operations = [
        migrations.CreateModel(
            name='orcidUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(help_text='whats yo name', max_length=512)),
                ('l_name', models.CharField(help_text="who's yo daddy", max_length=512)),
                ('full_name', models.CharField(max_length=512)),
                ('from_orcid', models.IntegerField(default=0, max_length=2)),
                ('orcid_x_attempted', models.DateTimeField(blank=True)),
                ('status', models.CharField(help_text='status in case of error on user', max_length=2048, null=True)),
                ('orcid', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='orcidUsersAlts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=512)),
                ('l_name', models.CharField(max_length=512)),
                ('full_name', models.CharField(max_length=512)),
                ('ou_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transfer.orcidusers')),
            ],
        ),
    ]
