# Generated by Django 5.2.6 on 2026-05-28 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0013_fsattempt_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fsattempt',
            name='oama_fk',
            field=models.ForeignKey(help_text='FK for oamessage', on_delete=django.db.models.deletion.CASCADE, to='transfer.oamessage'),
        ),
    ]
