# Generated by Django 4.0.4 on 2025-06-27 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0014_orcidusers_orcidusersalts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='orcidUsers',
            new_name='orcidUser',
        ),
        migrations.RenameModel(
            old_name='orcidUsersAlts',
            new_name='orcidUserAlts',
        ),
    ]
