# Generated by Django 4.0.4 on 2025-06-27 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0015_rename_orcidusers_orciduser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orciduser',
            name='from_orcid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orciduser',
            name='orcid',
            field=models.CharField(max_length=256, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='orciduser',
            name='orcid_x_attempted',
            field=models.DateTimeField(null=True),
        ),
    ]
