# Generated by Django 4.0.4 on 2025-06-27 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0016_alter_orciduser_from_orcid_alter_orciduser_orcid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orciduser',
            name='orcid',
            field=models.CharField(default=None, max_length=256, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='orciduser',
            name='orcid_x_attempted',
            field=models.DateTimeField(blank=True, default=None),
            preserve_default=False,
        ),
    ]
