# Generated by Django 4.0.4 on 2025-06-27 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0017_alter_orciduser_orcid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fsattempt',
            name='attempted',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='orciduser',
            name='orcid_x_attempted',
            field=models.DateTimeField(blank=True, default=None),
        ),
    ]
