# Generated by Django 4.0.4 on 2025-06-27 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0018_alter_fsattempt_attempted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fsattempt',
            name='attempted',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
