# Generated by Django 4.0.4 on 2025-06-27 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0019_alter_fsattempt_attempted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orciduser',
            name='orcid_x_attempted',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
