# Generated by Django 4.0.4 on 2025-06-27 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0020_alter_orciduser_orcid_x_attempted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orciduser',
            name='orcid',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
    ]
