# Generated by Django 4.0.4 on 2025-06-30 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0021_alter_orciduser_orcid'),
    ]

    operations = [
        migrations.AddField(
            model_name='orciduser',
            name='fs_id',
            field=models.IntegerField(default=0),
        ),
    ]
