# Generated by Django 4.0.4 on 2025-08-20 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0022_orciduser_fs_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orciduseralts',
            name='ou_fk',
        ),
        migrations.AlterField(
            model_name='fsattempt',
            name='oama_fk',
            field=models.ForeignKey(help_text='FK for oamessage', on_delete=django.db.models.deletion.CASCADE, to='transfer.oamessage'),
        ),
        migrations.DeleteModel(
            name='orcidUser',
        ),
        migrations.DeleteModel(
            name='orcidUserAlts',
        ),
    ]
