# Generated by Django 5.2.6 on 2025-12-12 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0023_remove_orciduseralts_ou_fk_alter_fsattempt_oama_fk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fsattempt',
            name='doi',
            field=models.CharField(default='0', help_text='for comparing duplicate/revisions', max_length=123),
        ),
    ]
