# Generated by Django 5.2.6 on 2026-06-04 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0014_alter_fsattempt_oama_fk'),
        ('transfer', '0024_fsattempt_doi'),
    ]

    operations = [
    ]
