# Generated by Django 5.2.6 on 2026-08-06 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0025_merge_0014_alter_fsattempt_oama_fk_0024_fsattempt_doi'),
    ]

    operations = [
        migrations.CreateModel(
            name='messageStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(default='', help_text='what went wrong. what went right.', null=True)),
                ('type', models.CharField(default='', help_text='type of error.', max_length=256, null=True)),
                ('status', models.CharField(default='', help_text='type of error.', max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='serviceCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(help_text='token for whatever', max_length=1024, null=True)),
                ('attempted', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(help_text='name for the service', max_length=1024)),
                ('client_id', models.CharField(help_text='client id for whatever', max_length=1024)),
                ('client_secret', models.CharField(help_text='client secret for whatever', max_length=1024)),
                ('url', models.CharField(help_text='url pointed at for the api calls. ie https://api.figshare.com/v2', max_length=1024, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='oaMessageAttempts',
        ),
        migrations.RenameField(
            model_name='fsattempt',
            old_name='fs_attempt_json',
            new_name='json',
        ),
        migrations.RenameField(
            model_name='fsattempt',
            old_name='oama_fk',
            new_name='oam_fk',
        ),
        migrations.RenameField(
            model_name='oamessage',
            old_name='message_json',
            new_name='json',
        ),
        migrations.RenameField(
            model_name='oamessage',
            old_name='message_id',
            new_name='oa_id',
        ),
        migrations.RenameField(
            model_name='oamessage',
            old_name='message_title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='fsattempt',
            name='note',
        ),
        migrations.RemoveField(
            model_name='fsattempt',
            name='status',
        ),
        migrations.RemoveField(
            model_name='oamessage',
            name='note',
        ),
        migrations.RemoveField(
            model_name='oamessage',
            name='status',
        ),
        migrations.AddField(
            model_name='messagestatus',
            name='fs_fk',
            field=models.ForeignKey(help_text='FK for fs', null=True, on_delete=django.db.models.deletion.CASCADE, to='transfer.fsattempt'),
        ),
        migrations.AddField(
            model_name='messagestatus',
            name='oam_fk',
            field=models.ForeignKey(help_text='FK for oa ', null=True, on_delete=django.db.models.deletion.CASCADE, to='transfer.oamessage'),
        ),
    ]
