# Generated by Django 5.2.6 on 2026-08-06 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0026_messagestatus_servicecredentials_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='useDevSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_dev', models.BooleanField(default=False, help_text='use dev settings?')),
            ],
        ),
        migrations.AddField(
            model_name='servicecredentials',
            name='is_dev',
            field=models.BooleanField(default=False, help_text='is this a dev token?'),
        ),
    ]
