# Generated by Django 5.2.6 on 2026-08-06 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0027_usedevsettings_servicecredentials_is_dev'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicecredentials',
            old_name='attempted',
            new_name='token_created',
        ),
    ]
