# Generated by Django 5.2.6 on 2026-08-06 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0028_rename_attempted_servicecredentials_token_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecredentials',
            name='token',
            field=models.CharField(blank=True, help_text='token for whatever', max_length=1024, null=True),
        ),
    ]
