# Generated by Django 5.2.6 on 2026-08-17 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0029_alter_servicecredentials_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagestatus',
            name='fs_fk',
        ),
        migrations.RemoveField(
            model_name='messagestatus',
            name='oam_fk',
        ),
        migrations.AddField(
            model_name='fsattempt',
            name='status',
            field=models.ForeignKey(help_text='FK for fs', null=True, on_delete=django.db.models.deletion.CASCADE, to='transfer.messagestatus'),
        ),
        migrations.AddField(
            model_name='oamessage',
            name='status',
            field=models.ForeignKey(help_text='FK for oa ', null=True, on_delete=django.db.models.deletion.CASCADE, to='transfer.messagestatus'),
        ),
        migrations.AlterField(
            model_name='servicecredentials',
            name='url',
            field=models.CharField(help_text='url pointed at for the api calls. ie https://api.figshare.com/v2/ (make sure to include final "/")', max_length=1024, null=True),
        ),
    ]
