# Generated by Django 5.2.6 on 2026-08-18 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0029_alter_servicecredentials_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagestatus',
            old_name='fs_fk',
            new_name='fs',
        ),
        migrations.RemoveField(
            model_name='messagestatus',
            name='oam_fk',
        ),
        migrations.AddField(
            model_name='messagestatus',
            name='oa',
            field=models.ForeignKey(help_text='FK for oa', null=True, on_delete=django.db.models.deletion.CASCADE, to='transfer.oamessage'),
        ),
        migrations.AlterField(
            model_name='servicecredentials',
            name='url',
            field=models.CharField(help_text='url pointed at for the api calls. ie https://api.figshare.com/v2/ (make sure to include final "/")', max_length=1024, null=True),
        ),
    ]
