# Generated by Django 5.2.6 on 2026-08-18 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0030_rename_fs_fk_messagestatus_fs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagestatus',
            name='fs',
            field=models.ForeignKey(help_text='FK for fs', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status', to='transfer.fsattempt'),
        ),
        migrations.AlterField(
            model_name='messagestatus',
            name='oa',
            field=models.ForeignKey(help_text='FK for oa', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status', to='transfer.oamessage'),
        ),
    ]
