# Generated by Django 5.1.7 on 2025-03-28 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='oaMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.IntegerField(help_text='id of the messages')),
                ('message_title', models.CharField(help_text='title of the article', max_length=1024)),
                ('status', models.CharField(help_text='status and maybe error message', max_length=2048)),
                ('attempted', models.DateTimeField(auto_now_add=True)),
                ('message_json', models.TextField(help_text='the json received')),
            ],
        ),
        migrations.CreateModel(
            name='fsAttempts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fs_id', models.IntegerField(help_text='filled in after successful upload to figshare')),
                ('status', models.CharField(help_text='status and maybe error message', max_length=2048)),
                ('link', models.CharField(help_text='link created for reference on fs', max_length=1024)),
                ('fs_attempt_json', models.TextField(help_text='the json attempt')),
                ('oa_id', models.ForeignKey(help_text='FK for token table', on_delete=django.db.models.deletion.CASCADE, to='transfer.oamessages')),
            ],
        ),
    ]
